[package]
name = "kerosene"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = "line-tables-only"

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[[bench]]
name = "receive"
harness = false
