[package]
name = "kerosene"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = "line-tables-only"

[dev-dependencies]
benchmark = { path = "crates/benchmark" }

[[bench]]
name = "receive"
harness = false

[[bench]]
name = "custom"
harness = false
